--CREATE EXTENSION pg_trgm;
SET pg_trgm.similarity_threshold = 0.25;
SELECT
    ALIM_CODE,
    ALIM_NOM_FR,
    SIMILARITY (ALIM_NOM_FR, 'Pain') AS SML
FROM
    ALIMENTS
WHERE
    ALIM_NOM_FR % 'Pain'
ORDER BY
    SML DESC,
    ALIM_CODE;

SELECT
    ALIM_CODE,
    ALIM_NOM_FR
FROM ALIMENTS
WHERE alim_nom_fr LIKE '%pain%';

SELECT
    ALIM_CODE,
    ALIM_NOM_FR
FROM ALIMENTS
WHERE alim_nom_fr ILIKE '%pain%';



--CREATE INDEX IDX_ALIMENTS_ALIM_NOM_FR_GIST ON ALIMENTS USING GIST (ALIM_NOM_FR GIST_TRGM_OPS);
--CREATE INDEX IDX_ALIMENTS_ALIM_NOM_FR_GIN ON ALIMENTS USING GIN (ALIM_NOM_FR GIN_TRGM_OPS);
--DROP INDEX IDX_ALIMENTS_ALIM_NOM_FR_GIST;
--DROP INDEX IDX_ALIMENTS_ALIM_NOM_FR_GIN;