CREATE OR REPLACE PROCEDURE vider_table_prod()
LANGUAGE PLPGSQL
AS $$
BEGIN
    TRUNCATE TABLE composition CASCADE ;
    TRUNCATE TABLE alim_moyen CASCADE ;
    TRUNCATE TABLE aliments CASCADE;
    TRUNCATE TABLE constituants CASCADE ;
    TRUNCATE TABLE sources CASCADE;
    TRUNCATE TABLE hierarchie CASCADE;
    TRUNCATE TABLE ssssgroupe CASCADE;
    TRUNCATE TABLE ssgroupe CASCADE;
    TRUNCATE TABLE groupe CASCADE;
END;
$$;