CREATE OR REPLACE VIEW VW_SOMME_GROUPES AS (
	SELECT
		*
	FROM
		HIERARCHIE H,
		GROUPE G,
		SSGROUPE SG,
		SSSSGROUPE SSG
	WHERE
		H.ALIM_GROUPE_CODE = G.ALIM_GROUPE_CODE
		AND H.ALIM_SSGROUPE_CODE = SG.ALIM_SSGROUPE_CODE
		AND H.ALIM_SSSSGROUPE_CODE = SSG.ALIM_SSSSGROUPE_CODE
);


CREATE OR REPLACE VIEW VW_ALIMENT_GROUPES AS (
SELECT
	ALM.alim_code,
	ALM.alim_nom_fr,
	G.alim_groupe_code,
	G.alim_groupe_fr,
	SG.alim_ssgroupe_code,
	SG.alim_ssgroupe_fr,
	SSG.alim_ssssgroupe_code,
	SSG.alim_ssssgroupe_fr
FROM
	ALIMENTS ALM
	INNER JOIN GROUPE G ON ALM.ALIM_GRP_CODE = G.ALIM_GROUPE_CODE
	INNER JOIN SSGROUPE SG ON ALM.ALIM_SSGRP_CODE = SG.ALIM_SSGROUPE_CODE
	INNER JOIN SSSSGROUPE SSG ON ALM.ALIM_SSSSGRP_CODE = SSG.ALIM_SSSSGROUPE_CODE
ORDER BY
    ALM.alim_code
);

CREATE OR REPLACE VIEW VW_ALL_DATA AS (
SELECT
	CP.ALIM_CODE,
	ALM_G.ALIM_NOM_FR,
	ALM_G.ALIM_GROUPE_CODE,
	ALM_G.ALIM_GROUPE_FR,
	ALM_G.ALIM_SSGROUPE_CODE,
	ALM_G.ALIM_SSGROUPE_FR,
	ALM_G.ALIM_SSSSGROUPE_CODE,
	ALM_G.ALIM_SSSSGROUPE_FR,
	CONST.CONST_CODE,
	CONST.CONST_NOM_FR,
	CP.TENEUR_BRUTE,
	CP.TENEUR_TYPE,
	CP.TENEUR_VALEUR,
	SRC.CODE_SOURCE,
	SRC.REF_CITATION
FROM
	COMPOSITION CP
	INNER JOIN (
		SELECT
			ALM.ALIM_CODE,
			ALM.ALIM_NOM_FR,
			G.ALIM_GROUPE_CODE,
			G.ALIM_GROUPE_FR,
			SG.ALIM_SSGROUPE_CODE,
			SG.ALIM_SSGROUPE_FR,
			SSG.ALIM_SSSSGROUPE_CODE,
			SSG.ALIM_SSSSGROUPE_FR
		FROM
			ALIMENTS ALM
			INNER JOIN GROUPE G ON ALM.ALIM_GRP_CODE = G.ALIM_GROUPE_CODE
			INNER JOIN SSGROUPE SG ON ALM.ALIM_SSGRP_CODE = SG.ALIM_SSGROUPE_CODE
			INNER JOIN SSSSGROUPE SSG ON ALM.ALIM_SSSSGRP_CODE = SSG.ALIM_SSSSGROUPE_CODE
	) ALM_G ON ALM_G.ALIM_CODE = CP.ALIM_CODE
	INNER JOIN CONSTITUANTS CONST ON CONST.CONST_CODE = CP.CONST_CODE
	LEFT JOIN SOURCES SRC ON SRC.CODE_SOURCE = CP.SOURCE_CODE
ORDER BY
    CP.ALIM_CODE, CONST.CONST_CODE
);

CREATE OR REPLACE VIEW VW_GROUPE_SSGROUPE_ID AS (
SELECT DISTINCT
    DENSE_RANK() OVER (
        ORDER BY
            HC.ALIM_GROUPE_CODE
        ) AS ID,
    HC.ALIM_SSGROUPE_CODE,
    COALESCE(SG.ALIM_SSGROUPE_FR, 'Non catégorisé')::varchar(75) AS ALIM_SSGROUPE_FR,
    COALESCE(SG.ALIM_SSGROUPE_ENG, 'Uncategorized')::varchar(75) AS ALIM_SSGROUPE_ENG

FROM
    HIERARCHIE HC
        INNER JOIN SSGROUPE SG ON HC.ALIM_SSGROUPE_CODE = SG.ALIM_SSGROUPE_CODE
ORDER BY
    ID,
    HC.ALIM_SSGROUPE_CODE
);

CREATE OR REPLACE VIEW VW_SSGROUPE_SSSSGROUPE_NUM AS (
SELECT
    HC.ALIM_SSGROUPE_CODE,
    SSG.ALIM_SSSSGROUPE_CODE,
    COALESCE(SSG.ALIM_SSSSGROUPE_FR, 'Non catégorisé')::varchar(75) AS ALIM_SSSSGROUPE_FR,
    COALESCE(SSG.ALIM_SSSSGROUPE_ENG, 'Uncategorized')::varchar(75) AS ALIM_SSSSGROUPE_ENG

FROM
    HIERARCHIE HC
        INNER JOIN SSSSGROUPE SSG ON HC.ALIM_SSSSGROUPE_CODE = SSG.ALIM_SSSSGROUPE_CODE
);